stages:
  - build

build-commit:
  stage: build
  image: alpine:edge
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_COMMIT_BRANCH
  before_script:
    - apk add --no-cache bash font-noto xz
    - apk add --no-cache rsvg-convert py3-pillow xcursorgen
  script:
    - ./build.sh -a -p
  artifacts:
    expire_in: 1 week
    paths:
      - built_themes/*.tar.xz
      - previews/*.png

build-tag:
  stage: build
  image: alpine:edge
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add --no-cache bash font-noto xz
    - apk add --no-cache rsvg-convert py3-pillow xcursorgen
  script:
    - ./build.sh -a -p
  after_script:
    - for ARCHIVE_FILE in built_themes/*.tar.xz; do echo "$CI_JOB_URL/artifacts/raw/$ARCHIVE_FILE" >> archive_links.txt; done
  artifacts:
    expire_in: never
    paths:
      - built_themes/*.tar.xz
      - previews/*.png
      - archive_links.txt

